import { FileImageTwoTone } from "@ant-design/icons";
import { Checkbox } from "antd";

export const KatalogData = [
    {
        key: "1",
        checkbox: <Checkbox />,
        rasm: <FileImageTwoTone />,
        tovarnomi: "sad",
        artikl: "da",
        shtrixkod: "da",
        turkum: "asd",
        yetkazibberish: "das",
        things: "23шт",
    },
    {
        key: "2",
        checkbox: <Checkbox />,
        rasm: <FileImageTwoTone />,
        tovarnomi: "sad",
        artikl: "da",
        shtrixkod: "da",
        turkum: "asd",
        yetkazibberish: "das",
        things: "23шт",
    },
    {
        key: "3",
        checkbox: <Checkbox />,
        rasm: <FileImageTwoTone />,
        tovarnomi: "sad",
        artikl: "da",
        shtrixkod: "da",
        turkum: "asd",
        yetkazibberish: "das",
        things: "23шт",
    },
    {
        key: "4",
        checkbox: <Checkbox />,
        rasm: <FileImageTwoTone />,
        tovarnomi: "sad",
        artikl: "da",
        shtrixkod: "da",
        turkum: "asd",
        yetkazibberish: "das",
        things: "23шт",
    },
    {
        key: "5",
        checkbox: <Checkbox />,
        rasm: <FileImageTwoTone />,
        tovarnomi: "sad",
        artikl: "da",
        shtrixkod: "da",
        turkum: "asd",
        yetkazibberish: "das",
        things: "23шт",
    },
    {
        key: "6",
        checkbox: <Checkbox />,
        rasm: <FileImageTwoTone />,
        tovarnomi: "sad",
        artikl: "da",
        shtrixkod: "da",
        turkum: "asd",
        yetkazibberish: "das",
        things: "23шт",
    },
    {
        key: "7",
        checkbox: <Checkbox />,
        rasm: <FileImageTwoTone />,
        tovarnomi: "sad",
        artikl: "da",
        shtrixkod: "da",
        turkum: "asd",
        yetkazibberish: "das",
        things: "23шт",
    },
    {
        key: "8",
        checkbox: <Checkbox />,
        rasm: <FileImageTwoTone />,
        tovarnomi: "sad",
        artikl: "da",
        shtrixkod: "da",
        turkum: "asd",
        yetkazibberish: "das",
        things: "23шт",
    },
    {
        key: "9",
        checkbox: <Checkbox />,
        rasm: <FileImageTwoTone />,
        tovarnomi: "sad",
        artikl: "da",
        shtrixkod: "da",
        turkum: "asd",
        yetkazibberish: "das",
        things: "23шт",
    },
    {
        key: "10",
        checkbox: <Checkbox />,
        rasm: <FileImageTwoTone />,
        tovarnomi: "sad",
        artikl: "da",
        shtrixkod: "da",
        turkum: "asd",
        yetkazibberish: "das",
        things: "23шт",
    },
    {
        key: "11",
        checkbox: <Checkbox />,
        rasm: <FileImageTwoTone />,
        tovarnomi: "sad",
        artikl: "da",
        shtrixkod: "da",
        turkum: "asd",
        yetkazibberish: "das",
        things: "23шт",
    },
    {
        key: "12",
        checkbox: <Checkbox />,
        rasm: <FileImageTwoTone />,
        tovarnomi: "sad",
        artikl: "da",
        shtrixkod: "da",
        turkum: "asd",
        yetkazibberish: "das",
        things: "23шт",
    },
    {
        key: "13",
        checkbox: <Checkbox />,
        rasm: <FileImageTwoTone />,
        tovarnomi: "sad",
        artikl: "da",
        shtrixkod: "da",
        turkum: "asd",
        yetkazibberish: "das",
        things: "23шт",
    },
    {
        key: "14",
        checkbox: <Checkbox />,
        rasm: <FileImageTwoTone />,
        tovarnomi: "sad",
        artikl: "da",
        shtrixkod: "da",
        turkum: "asd",
        yetkazibberish: "das",
        things: "23шт",
    },
    {
        key: "15",
        checkbox: <Checkbox />,
        rasm: <FileImageTwoTone />,
        tovarnomi: "sad",
        artikl: "da",
        shtrixkod: "da",
        turkum: "asd",
        yetkazibberish: "das",
        things: "23шт",
    },
    {
        key: "16",
        checkbox: <Checkbox />,
        rasm: <FileImageTwoTone />,
        tovarnomi: "sad",
        artikl: "da",
        shtrixkod: "da",
        turkum: "asd",
        yetkazibberish: "das",
        things: "23шт",
    },
    {
        key: "17",
        checkbox: <Checkbox />,
        rasm: <FileImageTwoTone />,
        tovarnomi: "sad",
        artikl: "da",
        shtrixkod: "da",
        turkum: "asd",
        yetkazibberish: "das",
        things: "23шт",
    },
    {
        key: "18",
        checkbox: <Checkbox />,
        rasm: <FileImageTwoTone />,
        tovarnomi: "sad",
        artikl: "da",
        shtrixkod: "da",
        turkum: "asd",
        yetkazibberish: "das",
        things: "23шт",
    },
    {
        key: "19",
        checkbox: <Checkbox />,
        rasm: <FileImageTwoTone />,
        tovarnomi: "sad",
        artikl: "da",
        shtrixkod: "da",
        turkum: "asd",
        yetkazibberish: "das",
        things: "23шт",
    },
    {
        key: "20",
        checkbox: <Checkbox />,
        rasm: <FileImageTwoTone />,
        tovarnomi: "ssaad",
        artikl: "sasda",
        shtrixkod: "adsda",
        turkum: "asadsad",
        yetkazibberish: "dsadas",
        things: "23шт",
    },
];

export const CustomersData = [
    {
        key: "1",
        checkbox: <Checkbox />,
        id: "516789",
        fish: "Suroj",
        telefon: "+998 99 999 99 99",
        guruhlar: "-",
        teglar: "-",
        xaridsummasi: "100000 UZS",
        oxirgixarid: "2.08.2024",
        tugilgankuni: "-",
        yaratilganvaqt: "02.08.2024",
    },
];

export const ImportData = [
    {
        key: "1",
        id: "164738",
        tovarnomi: `Product import`,
        dokon: "Store Avtodisk",
        soni: `10 `,
        summasi: "240 000 UZS",
        status: "Yakunlandi",
    },
];
